name: CI

on:
  push:
    branches:
    - develop
    - stable
  pull_request:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install gawk curl rlwrap emacs
    - name: Sanity check
      run: |
        make test
